### ISSUE TITLE
Pieces horizontal movement is too fast when key is held on.

### ISSUE THREAD

**Issue by malespiaut** [kwakzalver/zigtris#2]
Hello,

I've just tried your game, and I think that the horizontal movement of the pieces is too fast when you keep the left or right key pressed.

Maybe there should be a minimal delay (of a few frames, or a few milliseconds) between each movement.

Best regards.

**Comment by kwakzalver** [comment]
Good afternoon! 

In `src/window.zig:440` you can edit the `initial_delay` and the `repeat_delay` for the keyboard inputs. They are related to DAS and ARR, but hopefully less cryptic without the abbreviations.
The delays are hardcoded, but can be freely adjusted to signal the start of the repeating behavior as well as the repeats per time unit that should occur. Hope that helps!

If you think these values should be moved somewhere else, maybe even in a simple configuration file, then we could set up some extra work to solve the issue in other ways.

Thanks for taking the time to comment and have a nice weekend.
